services:
  db:
    ports:
      - 5432:5432
    container_name: postgresql-container
    image: postgres
    environment:
      - POSTGRES_DB=greenlight
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000

#для запуска docker-compose напишите команду "docker compose -f .\docker-compose.yaml up" в терминал
  backend:
    build: .
    container_name: category_tree_manager_bot
    ports:
      - 8089:8089
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/greenlight
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0000
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

