services:
  db:
    ports:
      - 5432:5432
    container_name: postgresql-container
    image: postgres
    environment:
      - POSTGRES-DB = MYDB2
      - POSTGRES-PASSWORD = admin2
      - POSTGRES-USER = admin2
      - POSTGRES_HOST_AUTH_METHOD = trust
    volumes:
      - C:\postgres_datapart:/var/lib/postgresql/data
    restart: always
  backend:
    build: .
    container_name: category_tree_manager_bot
    ports:
      - 8089:8089
    environment:
      db-url: jdbc:postgresql://db:5432/MYDB2
      db-username: admin2
      db-password: admin2
    depends_on:
      - db
    restart: always